// src/App.vue
<template>
  <div class="min-h-screen bg-dark-900 bg-grid-pattern overflow-x-hidden">
    <Header />
    <main class="animate-fadeIn">
      <HeroSection />
      <FeaturesSection />
      <AdvantagesSection />
      <DownloadSection />
      <AboutUsSection />
      <ContactSection />
    </main>
    <FooterSection />
  </div>
</template>

<script setup>
import Header from './components/Header.vue';
import HeroSection from './components/HeroSection.vue';
import FeaturesSection from './components/FeaturesSection.vue';
import AdvantagesSection from './components/AdvantagesSection.vue';
import DownloadSection from './components/DownloadSection.vue';
import AboutUsSection from './components/AboutUsSection.vue';
import ContactSection from './components/ContactSection.vue';
import FooterSection from './components/FooterSection.vue';
</script>

<style>
html {
  scroll-padding-top: 80px; /* 为固定导航条留出空间 */
}
</style>

// src/app/page.tsx
'use client';

import Header from '@/components/Header';
import HeroSection from '@/components/HeroSection';
import FeaturesSection from '@/components/FeaturesSection';
import AdvantagesSection from '@/components/AdvantagesSection';
import DownloadSection from '@/components/DownloadSection';
import AboutUsSection from '@/components/AboutUsSection';
import ContactSection from '@/components/ContactSection';
import FooterSection from '@/components/FooterSection';

export default function Home() {
  return (
    <div className="min-h-screen bg-light-200 bg-light-grid-pattern dark:bg-dark-900 dark:bg-grid-pattern overflow-x-hidden">
      <Header />
      <main className="animate-fadeIn">
        <HeroSection />
        <FeaturesSection />
        <AdvantagesSection />
        <DownloadSection />
        <AboutUsSection />
        {/* <ContactSection /> */}
      </main>
      <FooterSection />
    </div>
  );
}
